config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :wishlists
  resources :species
  resources :types
  resources :abilities
  resources :pokemons

  root "pokemons#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/views/species/_form.html.erb
<%= form_with(model: species, local: true) do |form| %>
  <% if species.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(species.errors.count, "error") %> prohibited this species from being saved:</h2>

      <ul>
      <% species.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :species_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/species/edit.html.erb
<h1>Editing Species</h1>

<%= render 'form', species: @species %>

<%= link_to 'Show', @species %> |
<%= link_to 'Back', species_index_path %>

app/views/species/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Species</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @species.each do |species| %>
      <tr>
        <td><%= species.name %></td>
        <td><%= link_to 'Show', species %></td>
        <td><%= link_to 'Edit', edit_species_path(species) %></td>
        <td><%= link_to 'Destroy', species, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Species', new_species_path %>

app/views/species/new.html.erb
<h1>New Species</h1>

<%= render 'form', species: @species %>

<%= link_to 'Back', species_index_path %>

app/views/species/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @species.name %>
</p>

<%= link_to 'Edit', edit_species_path(@species) %> |
<%= link_to 'Back', species_index_path %>