config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :wishlists
  resources :species
  resources :types
  resources :abilities
  resources :pokemons

  root "pokemons#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
	validate :image_size_validation
	mount_uploader :image, ImageUploader

	has_many :pokemon_abilities
	has_many :abilities, through: :pokemon_abilities

	has_many :capabilities, inverse_of: :pokemon, dependent: :destroy
  accepts_nested_attributes_for :capabilities, reject_if: :all_blank, allow_destroy: true

	has_many :pokemon_types
	has_many :types, through: :pokemon_types

	scope :by_types, ->(ids_ary) { joins(pokemon_types: :type).where("types.id" => ids_ary) }

	scope :by_species, -> specy { where(:specy => specy) }


	private
	  def image_size_validation
	    errors[:image] << "should be less than 3MB" if image.size > 3.0.megabytes
	  end
end

app/models/pokemon_type.rb
class PokemonType < ApplicationRecord
	belongs_to :pokemon
	belongs_to :type
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  has_scope :by_types, type: :array
  has_scope :by_species, type: :array
  # GET /pokemons
  # GET /pokemons.json
  def index
    @pokemons = if params[:term]
      Pokemon.where('name ILIKE ?', "%#{params[:term]}%")    
      
    else
      @pokemons = apply_scopes(Pokemon.order(:created_at => 'DESC'))

    end
     
  end

  # GET /pokemons/1
  # GET /pokemons/1.json
  def show
  end

  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
    @pokemon.capabilities.build 

  end

  # GET /pokemons/1/edit
  def edit
  end

  # POST /pokemons
  # POST /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully created.' }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1
  # PATCH/PUT /pokemons/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully updated.' }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1
  # DELETE /pokemons/1.json
  def destroy
    @pokemon.destroy
    respond_to do |format|
      format.html { redirect_to pokemons_url, notice: 'Pokemon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pokemon_params
      params.require(:pokemon).permit(:name, :image, :remove_image, :feet, :inches, :weight, {ability_ids: []}, {type_ids: []}, :specy, capabilities_attributes: [:id, :description, :_destroy])
    end
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/pokemons/_capability_fields.html.erb
<div class="nested-fields">
  <%= f.text_field :description, class: 'form-control' %>
  <%= link_to_remove_association "remove ability", f %>
  <br>
 </div>

app/views/pokemons/_form.html.erb
<%= form_with(model: pokemon, local: true) do |f| %>
  <% if pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
      <% pokemon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">

    <h2><%= f.label :name %></h2>
    <%= f.text_field :name, id: :pokemon_name, class: 'form-control' %>
  </div>

    
      <h2>Height & Weight</h2>
  <div class="flex">
    <%= f.label :feet %>
    <%= f.text_field :feet, class: 'form-control' %>
    <%= f.label :inches %>
    <%= f.text_field :inches, class: 'form-control' %>
    <%= f.label :weight %>
    <%= f.text_field :weight, class: 'form-control' %>
  </div>
  
  <h2>Species</h2>
    <%= f.text_field :specy, class: 'form-control' %>
       <h2>Abilities</h2> 
          <%= f.fields_for :capabilities do |capabilities| %>
            <%= render 'capability_fields', f: capabilities %>
          <% end %>

            <div class="links">
              <%= link_to_add_association "Add Ability", f, :capabilities %>
            </div>
            <br>
  <h2>Type</h2> 

   <%= hidden_field_tag "pokemon[type_ids][]", nil %>
        <% Type.order('name ASC').each do |type| %>
          <%= check_box_tag "pokemon[type_ids][]", type.id, @pokemon.type_ids.include?(type.id), id: dom_id(type) %>
          <%= label_tag dom_id(type), type.name %> 
          <br />

        <% end %>

     
    <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <% if f.object.image? %>
      <%= image_tag f.object.image.thumb.url %>
      <%= f.label :remove_image %>
      <%= f.check_box :remove_image %> 
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit "Create Pokemon", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/pokemons/edit.html.erb
<div class="form-container">
	<div class="form">
<h1>Editing Pokemon</h1>

<%= render 'form', pokemon: @pokemon %>

<%= link_to 'Show', @pokemon %> |
<%= link_to 'Back', pokemons_path %>
</div>
</div>

app/views/pokemons/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
 # of Cards: <span id="running-total"></span>
<%= link_to 'Add New Pokemon Card', new_pokemon_path, class:'btn btn-primary' %> <br><br>
<div class="flex-container">
    <% @pokemons.each do |pokemon| %>
  <div class="pokemon-box">
    <%= link_to pokemon do %>
     <%= image_tag pokemon.image.url if pokemon.image? %>
    <% end %>
      <h2><%= pokemon.name %></h2>
      <h3><% for type in pokemon.types %>
        <%= type.name %> | <% end %></h3>
      <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_pokemon_path(pokemon) %></td>
        <td><%= link_to 'Delete', pokemon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </div><!--/pokemon-box-->
    <% end %>
</div><!--/flex-container-->

<br>

</div>

app/views/pokemons/new.html.erb
<div class="form-container">
	<div class="form">
<h1>New Pokemon</h1>

<%= render 'form', pokemon: @pokemon %>

<%= link_to 'Back', pokemons_path %>
</div>
</div>

app/views/pokemons/show.html.erb
<div class="container show">
<p id="notice"><%= notice %></p>
 <h1><%= @pokemon.name %></h1>

 <%= image_tag @pokemon.image.url if @pokemon.image? %>

 <div class="table table-responsive">
 	<table class="table table-striped">
 	<tr>
		<td class="narrow">Height:</td> 
		<td><%= @pokemon.feet %>' <%= @pokemon.inches %>"</td>
	</tr>
	<tr>
		<td class="narrow">Weight:</td> 
		<td><%= @pokemon.weight %> pounds</td>
	</tr>
	<tr>
		<td class="narrow">Species:</td>
		 <td><%= @pokemon.specy %></td>
	<tr>
		<td class="narrow">Types:</td>
		<td><% for @type in @pokemon.types %>
			<%= @type.name %> | 
		<% end %></td>
	</tr>
	<tr>
		<td class="narrow">Abilities:</td>
		
			<td><% for @capability in @pokemon.capabilities %><%= @capability.description %> | <% end %></td>
	
</div>

<%= link_to 'Edit', edit_pokemon_path(@pokemon) %> |
<%= link_to 'Back', pokemons_path %>
</div>